name: Checkstyle

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Checkstyle
        run: |
          wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.18.1/checkstyle-10.18.1-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -DsuppressionFile=./codestyle/naver-checkstyle-suppressions.xml -c ./codestyle/naver-checkstyle-rules.xml src/

	  - name: Annotate PR with Checkstyle results
	    uses: staabm/annotate-pull-request-from-checkstyle@v1
	    with:
	      report_path: checkstyle-result.xml
